Feature/50 roles api bug
QAC-Portal/QA-Portal pull request #145
Opened 2019-12-11 14:40 UTC by renJoseph

Fixed the issue by removing user from keycloak config file and keycloak admin console, as the user was not in the database, which created bugs in the role api, preventing the manage roles page from loading correctly

2019-12-13 08:46 UTC, ianowenQA requested changes

2019-12-13 08:46 UTC, ianowenQA commented on qa-portal-angular/projects/portal-core/src/app/portal-header/portal-header.component.spec.ts
> +// import {async, ComponentFixture, fakeAsync, TestBed, tick} from '@angular/core/testing';
Revert this

2019-12-16 11:20 UTC, renJoseph commented
The fixes in this branch have been further improved in a more recent pull request

2019-12-17 11:02 UTC, ianowenQA approved these changes

2019-12-17 11:03 UTC, merged