Feature/#6 smaller keycloak resource manager classes
QAC-Portal/QA-Portal pull request #66
Opened 2019-12-03 14:40 UTC by Mbrookesy

Change to make it so it removes the UserResourceManager file in Cohort Api and splits it into 3 files.

- One for Email management
- One for user role management
- One for Cohort Management

Been tested through with similar results to live, However better to provide review regardless.

2019-12-10 14:04 UTC, ianowenQA requested changes

2019-12-10 14:04 UTC, ianowenQA commented on qa-portal-angular/package.json
>    "dependencies": {
Why was there a version bump? That seems out of scope for this issue.

2019-12-10 14:27 UTC, Mbrookesy commented on qa-portal-angular/package.json
>    "dependencies": {
Reverted the version file.

2019-12-13 08:34 UTC, ianowenQA approved these changes

2019-12-13 08:34 UTC, merged